repos:
  - repo: local
    hooks:
      - id: format
        name: Format
        language: system
        entry: make format
        pass_filenames: false
      - id: lint
        name: Lint
        language: system
        entry: make lint
        pass_filenames: false
