zookeeper:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: false
persistence:
  enabled: false
autoCreateTopicsEnable: true
resources:
  requests:
    cpu: 100m
    memory: 512Mi