Port: 8080

DeploymentConfig:
  EnvironmentType: local
  LogLevel: DEBUG
  MaxGoRoutines: 100

NewRelicConfig:
  Enabled: false
  AppName: dataset-service
  License: newrelic-license-secret
  IgnoreStatusCodes:
    - 400
    - 401
    - 403
    - 404
    - 405
    - 412

SentryConfig:
  Enabled: false
  DSN: xxx.xxx.xxx
  Labels:
    App: dataset-service

ObservationServiceConfig:
  GCPProject: gcp-project
  GCPServiceAccountKey: gcp-secret-name
  GCPServiceAccountSecret: sa.json
  # Optional to override image deployed by helms
  ObservationServiceImageTag: v0.0.1
  # Optional to override image deployed by helms
  FluentdImageTag: v0.0.1
  ObservationServiceHelmChartPath: https://github.com/caraml-dev/helm-charts/releases/download/observation-service-0.1.4/observation-service-0.1.4.tgz

MLPConfig:
  URL: http://localhost:8080/api/v1
