Port: 8080

DeploymentConfig:
  EnvironmentType: local
  LogLevel: DEBUG
  MaxGoRoutines: 100

NewRelicConfig:
  Enabled: false
  AppName: dataset-service
  License: newrelic-license-secret
  IgnoreStatusCodes:
    - 400
    - 401
    - 403
    - 404
    - 405
    - 412

SentryConfig:
  Enabled: false
  DSN: xxx.xxx.xxx
  Labels:
    App: dataset-service

ObservationServiceConfig:
  GCPProject: gcp-project
  ObservationServiceImageTag: v0.0.1
  FluentdImageTag: v0.0.1

MLPConfig:
  URL: http://localhost:8080/api/v1
