version: '3'
services:
  postgres:
    image: postgres:12.14-alpine
    ports:
      - 5432:5432
    environment:
    # These values should match dataset-service/config/local.yaml
      - POSTGRES_USER=timber
      - POSTGRES_PASSWORD=timber # dummy value for testing
      - POSTGRES_DATABASE=timber