name: Lint Charts

on:
  push:
    paths:
      - ".github/workflows/helm-chart.yml"
      - "infra/charts/**"
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/helm-chart.yml"
      - "infra/charts/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/config/ct.yaml | tr '\n' ' ')
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "charts_changed=$changed" >> $GITHUB_OUTPUT
          fi
  
      - name: Run chart-testing (lint)
        run: ct lint --config .github/config/ct.yaml
