name: publish-fluent-plugin-upi-logs
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish-fluent-plugin-upi-logs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: logwriter/fluent-plugin-upi-logs
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"
