name: CI

on:
  # Automatically run CI on Release and Pre-Release tags and main branch
  # (except changes to non-relevant paths)
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main
    paths-ignore:
      - "images/fluentd/**"

  # Automatically run CI on branches, that have active PR opened
  pull_request:
    branches:
      - main
    paths-ignore:
      - "images/fluentd/**"
  
  # To make it possible to trigger e2e CI workflow for any arbitrary git ref
  workflow_dispatch:

env:
  ARTIFACT_RETENTION_DAYS: 7
  GO_VERSION: 1.18
  GO_LINT_VERSION: v1.45.2

jobs:
  lint-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: '1.7.0'
          github_token: ${{ github.token }}
      - uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: 11
          maven-version: 3.8.4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-dataset-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-dataset-
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: dataset-service/proto
      - name: generate
        working-directory: dataset-service
        run: make setup generate
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - name: Lint Common module
        uses: golangci/golangci-lint-action@v2
        with:
          version: ${{ env.GO_LINT_VERSION }}
          working-directory: common
          args: --timeout 3m --verbose
      - name: Lint Observation Service module
        uses: golangci/golangci-lint-action@v2
        with:
          version: ${{ env.GO_LINT_VERSION }}
          working-directory: observation-service
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout 3m --verbose
      - name: Lint Dataset Service module
        uses: golangci/golangci-lint-action@v2
        with:
          version: ${{ env.GO_LINT_VERSION }}
          working-directory: dataset-service
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout 3m --verbose

  unit-tests-observation-service:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/api/.go
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Test Dependencies
        uses: ./.github/actions/setup-tests
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Run Observation Service test
        working-directory: observation-service
        run: make test-observation-service
  
  unit-tests-dataset-service:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/api/.go
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Test Dependencies
        uses: ./.github/actions/setup-tests
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Run Dataset Service test
        working-directory: dataset-service
        run: make test-dataset-service

  release-rules:
    runs-on: ubuntu-latest
    outputs:
      release-type: ${{ steps.release-rules.outputs.release-type }}
    steps:
      - uses: actions/checkout@v2
      - id: release-rules
        uses: ./.github/actions/release-rules

  release:
   # Automatically publish release and pre-release artifacts.
   #
   # As for dev releases, make it possible to publish artifacts
   # manually by approving 'deployment' in the 'manual' environment.
   #
   # Dev build can be released either from the 'main' branch or
   # by running this workflow manually with `workflow_dispatch` event.
    if: >-
      contains('release,pre-release', needs.release-rules.outputs.release-type)
        || ( github.event_name != 'pull_request' )
        || ( github.event.pull_request.head.repo.full_name == github.repository )
    needs:
      - lint-go
      - unit-tests-observation-service
      - unit-tests-dataset-service
      - release-rules
    uses: ./.github/workflows/release.yml
    with:
      environment: ${{ needs.release-rules.outputs.release-type == 'dev' && 'manual' || '' }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
